// Generated by tools/generate_species.py --images.
#pragma once
#include "lvgl.h"

extern const lv_image_dsc_t pikachu_large;
extern const lv_image_dsc_t pikachu_small;
extern const lv_image_dsc_t jigglypuff_large;
extern const lv_image_dsc_t jigglypuff_small;
extern const lv_image_dsc_t oddish_large;
extern const lv_image_dsc_t oddish_small;
extern const lv_image_dsc_t meowth_large;
extern const lv_image_dsc_t meowth_small;
extern const lv_image_dsc_t psyduck_large;
extern const lv_image_dsc_t psyduck_small;
extern const lv_image_dsc_t growlithe_large;
extern const lv_image_dsc_t growlithe_small;
extern const lv_image_dsc_t geodude_large;
extern const lv_image_dsc_t geodude_small;
extern const lv_image_dsc_t gastly_large;
extern const lv_image_dsc_t gastly_small;
extern const lv_image_dsc_t eevee_large;
extern const lv_image_dsc_t eevee_small;
