// Generated by tools/gen_starter_lvgl.py.
#pragma once

#include "lvgl.h"

extern const lv_image_dsc_t bulbasaur_large;
extern const lv_image_dsc_t bulbasaur_small;

extern const lv_image_dsc_t squirtle_large;
extern const lv_image_dsc_t squirtle_small;
