#include "ui_strings.h"

#include "lvgl.h"

#include <stddef.h>
#include <string.h>

typedef struct {
    const char *english;
    const char *chinese;
} translation_t;

static const char *lookup(
    city_language_t language,
    const char *english,
    const translation_t *translations,
    size_t count)
{
    if (language != CITY_LANGUAGE_SIMPLIFIED_CHINESE || english == NULL) {
        return english;
    }
    for (size_t i = 0; i < count; ++i) {
        if (strcmp(english, translations[i].english) == 0) {
            return translations[i].chinese;
        }
    }
    return english;
}

const char *ui_text(city_language_t language, const char *english)
{
    static const translation_t translations[] = {
        {"Let's play!", "一起玩吧！"},
        {"Look around", "四处看看"},
        {"Pokédex", "Pokédex"},
        {"My stamps", "我的印章"},
        {"Sound & screen", "设置"},
        {"Hold " LV_SYMBOL_UP " to turn screen off", "长按 " LV_SYMBOL_UP " 关闭屏幕"},
        {LV_SYMBOL_UP " / " LV_SYMBOL_DOWN " Choose\nPress OK to open",
         LV_SYMBOL_UP " / " LV_SYMBOL_DOWN " 选择\n按 OK 打开"},
        {"Health %u/%u", "体力 %u/%u"},
        {"Friendship %u", "亲密度 %u"},
        {"Ready to evolve!", "可以进化了！"},
        {"Best buddies!", "最好的伙伴！"},
        {"Go out together", "一起出发吧"},
        {"Pick your buddy", "选择你的伙伴"},
        {"Find a Pokemon!", "寻找宠物小精灵！"},
        {"Pick one in your Pokédex", "在 Pokédex 中选择"},
        {"Choose Look around to start", "选择“四处看看”开始"},

        {"Settings", "设置"},
        {"Saving...", "正在保存…"},
        {LV_SYMBOL_UP " Brighter / " LV_SYMBOL_DOWN " Dimmer\nPress OK when done",
         LV_SYMBOL_UP " 调亮 / " LV_SYMBOL_DOWN " 调暗\n完成后按 OK"},
        {LV_SYMBOL_UP " Louder / " LV_SYMBOL_DOWN " Softer\nPress OK when done",
         LV_SYMBOL_UP " 调高 / " LV_SYMBOL_DOWN " 调低\n完成后按 OK"},
        {LV_SYMBOL_UP " / " LV_SYMBOL_DOWN " Choose\nPress OK to pick",
         LV_SYMBOL_UP " / " LV_SYMBOL_DOWN " 选择\n按 OK 确认"},
        {"Language  %s", "语言  %s"},
        {"English", "English"},
        {"Simplified Chinese", "简体中文"},
        {"Sound volume  %u%%", "音量  %u%%"},
        {"Quiet mode  %s", "静音模式  %s"},
        {"Screen light  %u%%", "屏幕亮度  %u%%"},
        {"On", "开"},
        {"Off", "关"},
        {"Save and go back", "保存并返回"},
        {"Undo and go back", "放弃更改并返回"},
        {"Could not save. Try again.", "保存失败，请重试"},
        {"Please save these settings", "请保存这些设置"},
        {"Low battery: light at 30%", "电量低：亮度限制为 30%"},
        {"Sound is off", "声音已关闭"},
        {"Press OK to hear it", "按 OK 试听"},
        {"Save to keep your changes", "保存后设置才会生效"},
        {"Hold OK to undo changes", "长按 OK 放弃更改"},

        {"My stamps", "我的印章"},
        {LV_SYMBOL_UP " / " LV_SYMBOL_DOWN " Turn page\nPress OK to go home",
         LV_SYMBOL_UP " / " LV_SYMBOL_DOWN " 翻页\n按 OK 返回首页"},
        {"Stamps %u/%u   Page %u/%u", "印章 %u/%u   第 %u/%u 页"},
        {"Could not open your stamps", "无法打开印章册"},
        {"Found %u/%u   Have %u/%u", "发现 %u/%u   拥有 %u/%u"},
        {"Could not open Pokédex", "无法打开 Pokédex"},
        {"Place %02u", "地点 %02u"},
        {"Next: catch a Pokemon", "下一步：捕获一只宠物小精灵"},
        {"Next: visit %u places", "下一步：探索 %u 个地点"},
        {"Next: %s %s", "下一步：%s%s"},
        {"Next: evolve %s", "下一步：让%s进化"},
        {"You found them all!", "全部发现了！"},
        {"Could not open your saves", "无法打开存档"},
        {"catch", "捕获"},
        {"find", "寻找"},

        {"Looking around...", "正在四处寻找…"},
        {"Please wait", "请稍候"},
        {"Is this a new place?", "这是新地点吗？"},
        {"Again in 20s", "20 秒后再次确认"},
        {"Again in %lus", "%lu 秒后再次确认"},
        {"Checking now...", "正在再次确认…"},
        {"Checking this place again", "再确认一次这里的环境"},
        {"Let's try again", "再试一次吧"},
        {"Press OK to go home", "按 OK 返回首页"},
        {"Move a bit, then try again", "移动一段距离后重试"},
        {"In the wild", "野外探索"},
        {"Press OK to look around\n" LV_SYMBOL_UP " Go home",
         "按 OK 四处看看\n" LV_SYMBOL_UP " 返回首页"},
        {LV_SYMBOL_UP " Go home", LV_SYMBOL_UP " 返回首页"},
        {"One try every 30 minutes", "每 30 分钟可尝试一次"},
        {"Leaving counts as your try", "离开也会消耗本次机会"},
        {"Restarting may add 30 min", "重启可能重新等待 30 分钟"},
        {"Wait %02u:%02u", "等待 %02u:%02u"},
        {"Ready!", "可以开始！"},
        {"Time to charge", "该充电了"},
        {"Please charge before playing", "充电后再继续探索"},
        {"Wait here a moment", "请在这里稍等"},
        {"Then try Look around again", "然后再次四处看看"},
        {"Try looking again", "请重新寻找"},
        {"Press OK to try again\n" LV_SYMBOL_UP " Go home",
         "按 OK 重试\n" LV_SYMBOL_UP " 返回首页"},
        {"Could not look around.", "无法扫描周围环境"},
        {"Stamp not saved", "印章保存失败"},
        {"This stamp was not saved.", "这个印章尚未保存"},
        {"Stamp book is full", "印章册已满"},
        {"Your old stamps are safe.", "已有印章不会被覆盖"},

        {"Found %s", "发现了%s！"},
        {"Type: %s", "属性：%s"},
        {"New stamp! Place %02u", "新印章！地点 %02u"},
        {"You have one!", "已经拥有"},
        {"Not caught yet", "尚未捕获"},
        {"You found someone new!", "发现了新的宠物小精灵！"},
        {"Catch", "捕获"},
        {"Leave", "离开"},
        {"Your first catch", "第一次捕获"},
        {"Press OK to start\n" LV_SYMBOL_UP " Go back",
         "按 OK 开始\n" LV_SYMBOL_UP " 返回"},
        {"When you see NOW,", "看到“现在”时，"},
        {"press OK to throw.", "按 OK 投球。"},
        {"3 tries in 15 seconds", "15 秒内有 3 次机会"},
        {"Hold OK to stop playing", "长按 OK 停止捕获"},
        {"Catch %s", "捕获%s"},
        {"Press OK to throw", "按 OK 投球"},
        {"WAIT", "等待"},
        {"NOW", "现在"},
        {"%u tries left. Wait for NOW", "剩余 %u 次，等待“现在”"},
        {"Hold OK to stop", "长按 OK 停止"},
        {"Here it goes!", "投出去啦！"},
        {"Watch your ball!", "看好精灵球！"},
        {"Will it stay?", "能抓住吗？"},
        {"One... Two... Three...", "一次…两次…三次…"},
        {"You caught it!", "捕获成功！"},
        {"Press OK for Pokédex", "按 OK 查看 Pokédex"},
        {"Saved in your Pokédex", "已保存到 Pokédex"},
        {"Friendship +%u", "亲密度 +%u"},
        {"Pick your new buddy!", "选择你的新伙伴！"},
        {"Next: pick a buddy", "下一步：选择伙伴"},
        {"Next: look at My stamps", "下一步：查看我的印章"},
        {"It got away!", "它逃走了！"},
        {"Time is up! Watch for NOW.", "时间到了！注意“现在”提示。"},
        {"No throw", "没有投球"},
        {"Time up", "超时"},
        {"Too early", "太早了"},
        {"Too late", "太晚了"},
        {"%u %s  %u sec  %s", "%u 次  %u 秒  %s"},
        {"try", "机会"},
        {"tries", "机会"},
        {"Press OK!", "按 OK！"},
        {"Wait", "等待"},
        {"You left it alone", "你放它离开了"},
        {"See you, %s!", "再见，%s！"},

        {"Press OK to open\nHold OK to go home",
         "按 OK 打开\n长按 OK 返回首页"},
        {"Go home", "返回首页"},
        {"Evolved", "已进化"},
        {"Caught", "已捕获"},
        {"Found", "已发现"},
        {"Grew by evolving", "通过进化获得"},
        {"Caught %lu", "已捕获 %lu"},
        {"Found %u/%u   Page %u/%u", "发现 %u/%u   第 %u/%u 页"},
        {"Not found yet", "尚未发现"},
        {"Press OK to go back", "按 OK 返回"},
        {"Look around for Pokemon", "四处寻找宠物小精灵"},
        {"Some Pokemon must evolve", "有些宠物小精灵需要进化"},
        {"Look at My stamps for help", "查看我的印章获得提示"},
        {LV_SYMBOL_UP " Make buddy  " LV_SYMBOL_DOWN " Back\nPress OK for choices",
         LV_SYMBOL_UP " 设为伙伴  " LV_SYMBOL_DOWN " 返回\n按 OK 查看选项"},
        {"Have %lu", "拥有 %lu"},
        {"Place --", "地点 --"},
        {"Wild", "野外"},
        {"Strongest: Health %u/%u", "最强个体：体力 %u/%u"},
        {"Attack %u   Defense %u", "攻击 %u   防御 %u"},
        {"Friendship %u/100%s", "亲密度 %u/100%s"},
        {"  Buddy", "  伙伴"},
        {"Try to catch this Pokemon", "试着捕获这只宠物小精灵"},

        {"Buddy choices", "伙伴选项"},
        {"Your strongest one", "当前最强个体"},
        {"Health is full", "体力已满"},
        {"Needs healing", "需要恢复体力"},
        {"Heal", "恢复体力"},
        {"My Pokemon", "我的宠物小精灵"},
        {"Evolve", "进化"},
        {"Let go", "放生"},
        {"Go back", "返回"},
        {"My %s", "我的%s"},
        {LV_SYMBOL_UP " / " LV_SYMBOL_DOWN " Pick Pokemon\nPress OK to go back",
         LV_SYMBOL_UP " / " LV_SYMBOL_DOWN " 选择宠物小精灵\n按 OK 返回"},
        {"Pokemon %u of %u", "第 %u/%u 只"},
        {"From your old save", "来自旧存档"},
        {"Grew through evolution", "通过进化获得"},
        {"Caught in the wild", "在野外捕获"},
        {"Caught at Place %02u", "在地点 %02u 捕获"},
        {"Stats may be shared", "个体数据可能来自旧记录"},
        {"These are this one's stats", "这是这只的个体数据"},

        {"Let this one go?", "确定放生吗？"},
        {"This is #%u. %u will stay.", "这是第 %u 只，仍会保留 %u 只。"},
        {"This is your last one.", "这是最后一只。"},
        {"Its friendship starts over.", "它的亲密度将被清除。"},
        {"Its visits start over too.", "它的地点记录也会清除。"},
        {"> Let go <", "> 放生 <"},
        {"> Keep it <", "> 保留 <"},
        {"Keep it", "保留"},
        {"Pick a Pokemon", "选择宠物小精灵"},
        {"Old save: shared stats", "旧存档：共享个体数据"},
        {"Keep all your Pokemon", "保留全部宠物小精灵"},
        {"Hold OK to go back", "长按 OK 返回"},
        {"> Go back <", "> 返回 <"},
        {"You let it go", "已经放生"},
        {"%s left. You have %lu.", "已放生%s，还拥有 %lu 只。"},
        {"%s is free now.", "%s已经自由了。"},

        {"Time to evolve?", "要进化吗？"},
        {"Grow into %s", "进化为%s"},
        {"Friendship %u/30", "亲密度 %u/30"},
        {"Places visited %u/3", "探索地点 %u/3"},
        {"Already evolved", "已经进化"},
        {"Pick this buddy first", "请先把它设为伙伴"},
        {"Your buddy is ready!", "伙伴已经可以进化！"},
        {"Catch Pokemon together", "一起捕获宠物小精灵"},
        {"> Evolve <", "> 进化 <"},
        {"Not ready yet", "尚未满足条件"},
        {"> Later <", "> 稍后 <"},
        {"Later", "稍后"},
        {"Your buddy evolved!", "伙伴进化了！"},
        {"Saved! Meet your new buddy.", "已保存！见见进化后的伙伴吧。"},

        {"Could not save", "保存失败"},
        {"Go home without saving?", "不保存并返回首页？"},
        {"Could not save this change.", "这次更改未能保存。"},
        {"Your buddy did not change.", "伙伴没有改变。"},
        {"Could not save the healing.", "体力恢复未能保存。"},
        {"Your Pokemon is still here.", "宠物小精灵仍然保留。"},
        {"Could not save this one.", "发现记录未能保存。"},
        {"Could not save your catch.", "捕获记录未能保存。"},
    };
    return lookup(
        language, english, translations,
        sizeof(translations) / sizeof(translations[0]));
}

const char *ui_species_name(city_language_t language, const char *english)
{
    static const translation_t translations[] = {
        {"Bulbasaur", "妙蛙种子"},
        {"Ivysaur", "妙蛙草"},
        {"Charmander", "小火龙"},
        {"Charmeleon", "火恐龙"},
        {"Squirtle", "杰尼龟"},
        {"Wartortle", "卡咪龟"},
        {"Pikachu", "皮卡丘"},
        {"Jigglypuff", "胖丁"},
        {"Oddish", "走路草"},
        {"Meowth", "喵喵"},
        {"Psyduck", "可达鸭"},
        {"Growlithe", "卡蒂狗"},
        {"Geodude", "小拳石"},
        {"Gastly", "鬼斯"},
        {"Eevee", "伊布"},
    };
    return lookup(
        language, english, translations,
        sizeof(translations) / sizeof(translations[0]));
}

const char *ui_species_type(city_language_t language, const char *english)
{
    static const translation_t translations[] = {
        {"Grass / Poison", "草 / 毒"},
        {"Fire", "火"},
        {"Water", "水"},
        {"Electric", "电"},
        {"Normal / Fairy", "一般 / 妖精"},
        {"Normal", "一般"},
        {"Rock / Ground", "岩石 / 地面"},
        {"Ghost / Poison", "幽灵 / 毒"},
    };
    return lookup(
        language, english, translations,
        sizeof(translations) / sizeof(translations[0]));
}

const char *ui_species_description(city_language_t language, const char *english)
{
    static const translation_t translations[] = {
        {"The seed on its back stores food to help it grow.",
         "背上的种子储存营养，帮助它成长。"},
        {"Sunlight helps it grow strong and makes its back bud grow.",
         "阳光让它变强，也让背上的花苞成长。"},
        {"The flame on its tail gets dim when it feels weak.",
         "虚弱时，它尾巴上的火焰会变暗。"},
        {"Its hot tail can warm the air around it.",
         "炽热的尾巴能让周围的空气升温。"},
        {"Its shell gets hard as it grows. It can spray strong foam.",
         "成长后甲壳会变硬，还能喷出强力泡沫。"},
        {"Its fluffy tail is a sign of a long life.",
         "蓬松的尾巴象征着长寿。"},
        {"It keeps electric power in its cheeks.",
         "它会把电力储存在脸颊里。"},
        {"Its soft song can make others fall asleep.",
         "轻柔的歌声能让听者入睡。"},
        {"At night, it walks on its two roots.",
         "到了夜晚，它会用两条根行走。"},
        {"It rests in the day and walks around its home at night.",
         "白天休息，夜晚在自己的地盘四处走动。"},
        {"When its head hurts badly, strange powers can come out.",
         "头痛得厉害时，会释放出神奇的力量。"},
        {"It is brave, even against much bigger Pokemon.",
         "即使面对更大的宠物小精灵，它也十分勇敢。"},
        {"It looks like a rock. Watch where you step!",
         "它看起来就像石头，走路时要小心！"},
        {"Its body is made of gas. It can wrap around others.",
         "身体由气体构成，可以包围其他生物。"},
        {"It can evolve into many forms to live in different places.",
         "它能进化成多种形态，适应不同环境。"},
    };
    return lookup(
        language, english, translations,
        sizeof(translations) / sizeof(translations[0]));
}
