#!/usr/bin/env python3
"""Convert additional starter artwork into flash-backed LVGL assets."""

from pathlib import Path

from PIL import Image


ROOT = Path(__file__).resolve().parents[1]
SPECIES = {
    "bulbasaur": {
        "source": ROOT / "demo" / "assets" / "bulbasaur.png",
        "url": (
            "https://www.pokemon.com/static-assets/content-assets/"
            "cms2/img/pokedex/full/001.png"
        ),
    },
    "squirtle": {
        "source": ROOT / "demo" / "assets" / "squirtle.png",
        "url": (
            "https://www.pokemon.com/static-assets/content-assets/"
            "cms2/img/pokedex/full/007.png"
        ),
    },
}
OUT_C = ROOT / "main" / "assets" / "starter_sprites.c"
OUT_H = ROOT / "main" / "assets" / "starter_sprites.h"


def rgb565(red: int, green: int, blue: int) -> int:
    return ((red >> 3) << 11) | ((green >> 2) << 5) | (blue >> 3)


def emit_asset(lines: list[str], symbol: str, image: Image.Image) -> None:
    color_bytes: list[int] = []
    alpha_bytes: list[int] = []
    for red, green, blue, alpha in image.getdata():
        value = rgb565(red, green, blue)
        color_bytes.extend((value & 0xFF, value >> 8))
        alpha_bytes.append(alpha)

    data = color_bytes + alpha_bytes
    lines.append(
        "static LV_ATTRIBUTE_MEM_ALIGN LV_ATTRIBUTE_LARGE_CONST "
        f"const uint8_t {symbol}_map[] = {{"
    )
    for offset in range(0, len(data), 16):
        values = ", ".join(f"0x{value:02X}" for value in data[offset : offset + 16])
        lines.append(f"    {values},")
    lines.extend(
        [
            "};",
            "",
            f"const lv_image_dsc_t {symbol} = {{",
            "    .header = {",
            "        .magic = LV_IMAGE_HEADER_MAGIC,",
            "        .cf = LV_COLOR_FORMAT_RGB565A8,",
            "        .flags = 0,",
            f"        .w = {image.width},",
            f"        .h = {image.height},",
            f"        .stride = {image.width * 2},",
            "    },",
            f"    .data_size = sizeof({symbol}_map),",
            f"    .data = {symbol}_map,",
            "};",
            "",
        ]
    )


def main() -> None:
    resample = getattr(Image, "Resampling", Image).LANCZOS
    header = [
        "// Generated by tools/gen_starter_lvgl.py.",
        "#pragma once",
        "",
        '#include "lvgl.h"',
        "",
    ]
    source_lines = [
        "// Generated by tools/gen_starter_lvgl.py.",
        "// RGB565 pixels are followed by one A8 plane.",
        "",
        '#include "starter_sprites.h"',
        "",
    ]
    total = 0
    for name, metadata in SPECIES.items():
        source = Image.open(metadata["source"]).convert("RGBA")
        source_lines.append(f"// Source: {metadata['url']}")
        for suffix, size in (("large", 110), ("small", 82)):
            symbol = f"{name}_{suffix}"
            header.append(f"extern const lv_image_dsc_t {symbol};")
            image = source.resize((size, size), resample)
            emit_asset(source_lines, symbol, image)
            total += size * size * 3
        header.append("")

    OUT_H.write_text("\n".join(header), encoding="ascii")
    OUT_C.write_text("\n".join(source_lines), encoding="ascii")
    print(f"generated {OUT_C.relative_to(ROOT)} ({total} bytes of image data)")


if __name__ == "__main__":
    main()
