#!/usr/bin/env python3
"""Convert official Pokedex artwork into flash-backed LVGL RGB565A8 assets."""

from pathlib import Path

from PIL import Image


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "demo" / "assets" / "charmander.png"
OUT_C = ROOT / "main" / "assets" / "charmander_sprite.c"
OUT_H = ROOT / "main" / "assets" / "charmander_sprite.h"
SOURCE_URL = (
    "https://www.pokemon.com/static-assets/content-assets/"
    "cms2/img/pokedex/full/004.png"
)


def rgb565(red: int, green: int, blue: int) -> int:
    return ((red >> 3) << 11) | ((green >> 2) << 5) | (blue >> 3)


def emit_asset(lines: list[str], symbol: str, image: Image.Image) -> None:
    color_bytes: list[int] = []
    alpha_bytes: list[int] = []
    for red, green, blue, alpha in image.getdata():
        value = rgb565(red, green, blue)
        color_bytes.extend((value & 0xFF, value >> 8))
        alpha_bytes.append(alpha)

    data = color_bytes + alpha_bytes
    lines.append(
        "static LV_ATTRIBUTE_MEM_ALIGN LV_ATTRIBUTE_LARGE_CONST "
        f"const uint8_t {symbol}_map[] = {{"
    )
    for offset in range(0, len(data), 16):
        values = ", ".join(f"0x{value:02X}" for value in data[offset : offset + 16])
        lines.append(f"    {values},")
    lines.extend(
        [
            "};",
            "",
            f"const lv_image_dsc_t {symbol} = {{",
            "    .header = {",
            "        .magic = LV_IMAGE_HEADER_MAGIC,",
            "        .cf = LV_COLOR_FORMAT_RGB565A8,",
            "        .flags = 0,",
            f"        .w = {image.width},",
            f"        .h = {image.height},",
            f"        .stride = {image.width * 2},",
            "    },",
            f"    .data_size = sizeof({symbol}_map),",
            f"    .data = {symbol}_map,",
            "};",
            "",
        ]
    )


def main() -> None:
    source = Image.open(SOURCE).convert("RGBA")
    resample = getattr(Image, "Resampling", Image).LANCZOS
    variants = {
        "charmander_large": source.resize((110, 110), resample),
        "charmander_small": source.resize((82, 82), resample),
    }

    header = [
        "// Generated by tools/gen_charmander_lvgl.py.",
        "#pragma once",
        "",
        '#include "lvgl.h"',
        "",
        "extern const lv_image_dsc_t charmander_large;",
        "extern const lv_image_dsc_t charmander_small;",
        "",
    ]
    OUT_H.write_text("\n".join(header), encoding="ascii")

    source_lines = [
        "// Generated by tools/gen_charmander_lvgl.py.",
        f"// Source: {SOURCE_URL}",
        "// RGB565 pixels are followed by one A8 plane.",
        "",
        '#include "charmander_sprite.h"',
        "",
    ]
    for symbol, image in variants.items():
        emit_asset(source_lines, symbol, image)
    OUT_C.write_text("\n".join(source_lines), encoding="ascii")

    total = sum(image.width * image.height * 3 for image in variants.values())
    print(f"generated {OUT_C.relative_to(ROOT)} ({total} bytes of image data)")


if __name__ == "__main__":
    main()
