#!/usr/bin/env python3
"""Compile verified, pinned Ogg cries into flash-resident 16 kHz mono PCM.

Run with --ffmpeg /path/to/ffmpeg. --check needs no decoder or network.
"""
import argparse
import hashlib
import json
from pathlib import Path
import struct
import subprocess
import tempfile

ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / 'content/cries'
OUTPUT = ROOT / 'main/assets/pokemon_cries.inc'


def digest(data):
    return hashlib.sha256(data).hexdigest()


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--ffmpeg', default='ffmpeg')
    parser.add_argument('--check', action='store_true')
    parser.add_argument('--reuse-pcm', action='store_true', help='Rebuild the table from hash-verified existing PCM')
    args = parser.parse_args()
    manifest = json.loads((ASSETS / 'manifest.json').read_text())
    species = json.loads((ROOT / 'content/species.json').read_text())['species']
    assert [(s['id'], s['name']) for s in species] == [(s['id'], s['name']) for s in manifest['species']]
    chunks = ['/* Generated by tools/generate_cries.py; see content/cries/SOURCES.md. */']
    total = 0
    for row in manifest['species']:
        sid = row['id']
        expected_url = (f'https://raw.githubusercontent.com/PokeAPI/cries/'
                        f'{manifest["repository_commit"]}/cries/pokemon/latest/{sid}.ogg')
        original = row.get('origin') == 'original'
        if original:
            assert sid >= 60000 and row['license'] == 'CC0-1.0'
            assert row['source_url'] == 'project:tools/generate_mossbit.py'
        else:
            assert row['source_url'] == expected_url, sid
        ogg = ASSETS / f'{sid}.ogg'
        pcm = ASSETS / f'{sid}.pcm'
        if not original:
            assert digest(ogg.read_bytes()) == row['source_sha256'], sid
        if not args.check and not args.reuse_pcm and not original:
            with tempfile.TemporaryDirectory() as directory:
                out = Path(directory) / 'cry.pcm'
                subprocess.run([args.ffmpeg, '-nostdin', '-v', 'error', '-i', str(ogg),
                                '-ac', '1', '-ar', '16000', '-acodec', 'pcm_s16le',
                                '-f', 's16le', str(out)], check=True)
                pcm.write_bytes(out.read_bytes())
            row['pcm_sha256'] = digest(pcm.read_bytes())
            row['samples'] = pcm.stat().st_size // 2
        data = pcm.read_bytes()
        assert digest(data) == row['pcm_sha256'] and len(data) == row['samples'] * 2, sid
        assert 1600 <= row['samples'] <= 64000, sid
        samples = struct.unpack(f'<{row["samples"]}h', data)
        assert max(abs(s) for s in samples) > 100, sid
        total += len(data)
        chunks.append(f'static const int16_t cry_{sid}[] = {{')
        chunks.extend('    ' + ','.join(str(s) for s in samples[n:n+16]) + ','
                      for n in range(0, len(samples), 16))
        chunks.append('};')
    assert total <= 700000, 'Audio flash budget exceeded'
    chunks.append('static const pokemon_cry_t cries[] = {')
    chunks.extend(f'    {{{r["id"]}, cry_{r["id"]}, sizeof(cry_{r["id"]}) / sizeof(int16_t)}},'
                  for r in manifest['species'])
    chunks.append('};\n')
    generated = '\n'.join(chunks)
    if args.check:
        assert OUTPUT.read_text() == generated, 'Generated audio table is stale'
    else:
        OUTPUT.write_text(generated)
        manifest['format'] = dict(sample_rate=16000, channels=1, bits=16, encoding='signed little-endian PCM')
        (ASSETS / 'manifest.json').write_text(json.dumps(manifest, indent=2) + '\n')
    print(f'Validated {len(species)} species cries; PCM flash bytes={total}')


if __name__ == '__main__':
    main()
