#!/usr/bin/env python3
"""Generate the bounded domain catalog and flash-backed artwork from one source."""
import argparse
import json
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
def outputs():
    data = json.loads((ROOT/'content/species.json').read_text())
    rows = data['species']
    assert 3 <= len(rows) <= 32
    assert len({r['id'] for r in rows}) == len(rows)
    assert [r['id'] for r in rows[:3]] == [1,4,7]
    for r in rows:
        assert 0 < r['id'] < 65535 and r['pool'] in (0,1,2)
        assert all(0 < r[k] <= 240 for k in ('hp','attack','defense'))
        assert isinstance(r['wild'],bool)
    header = '// Generated by tools/generate_species.py.\n#pragma once\n'
    header += f'#define CITY_SPECIES_COUNT {len(rows)}U\n#define CITY_CATALOG_VERSION {data["version"]}U\n'
    header += ''.join(f'#define CITY_SPECIES_{r["name"].upper()} {r["id"]}U\n' for r in rows)
    table = '// Generated by tools/generate_species.py.\nstatic const city_species_definition_t species_definitions[CITY_SPECIES_COUNT] = {\n'
    for r in rows:
        table += '    {'+f'.species_id={r["id"]}, .name={json.dumps(r["name"])}, .element={json.dumps(r["element"])}, .description={json.dumps(r["description"])}, .base_hp={r["hp"]}, .base_attack={r["attack"]}, .base_defense={r["defense"]}, .place_pool={r["pool"]}, .wild_eligible={str(r["wild"]).lower()}'+'},\n'
    table += '};\n'
    refs = '// Generated by tools/generate_species.py.\n'
    refs += ''.join(f'    {{{r["id"]}, &{r["name"].lower()}_large, &{r["name"].lower()}_small}},\n' for r in rows)
    return rows, {ROOT/'components/city_domain/include/species_catalog.h':header,
                  ROOT/'components/city_domain/src/species_catalog.inc':table,
                  ROOT/'main/assets/species_images.inc':refs}
def main():
    parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');parser.add_argument('--images',action='store_true');args=parser.parse_args()
    rows,files=outputs()
    if args.images:
        from PIL import Image
        from gen_starter_lvgl import emit_asset
        lines=['// Generated by tools/generate_species.py --images.','#include "roster_sprites.h"','']
        header=['// Generated by tools/generate_species.py --images.','#pragma once','#include "lvgl.h"','']
        for r in rows[3:]:
            src=Image.open(ROOT/'demo/assets'/f'{r["name"].lower()}.png').convert('RGBA')
            lines.append('// Source: '+r['artwork'])
            for suffix,size in [('large',110),('small',82)]:
                symbol=f'{r["name"].lower()}_{suffix}'
                emit_asset(lines,symbol,src.resize((size,size),Image.Resampling.LANCZOS))
                header.append(f'extern const lv_image_dsc_t {symbol};')
        files[ROOT/'main/assets/roster_sprites.c']='\n'.join(lines)+'\n'
        files[ROOT/'main/assets/roster_sprites.h']='\n'.join(header)+'\n'
    for p,text in files.items():
        if args.check:
            assert p.read_text()==text, f'Stale generated file: {p}'
        else: p.write_text(text)
if __name__=='__main__': main()
